version: '3.8'

services:
  # Base de datos PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: emotional_diary_db
    environment:
      POSTGRES_DB: emotional_diary
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Jkanime123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - emotional_diary_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # pgAdmin - Interfaz web para administrar PostgreSQL
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: emotional_diary_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - emotional_diary_network
    depends_on:
      - postgres
    restart: unless-stopped

  # Aplicación Node.js
  app:
    build: .
    container_name: emotional_diary_backend
    environment:
      NODE_ENV: development
      PORT: 5000
      DATABASE_URL: postgres://postgres:Jkanime123@postgres:5432/emotional_diary
      JWT_SECRET: your_jwt_secret_here
    ports:
      - "5001:5000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - emotional_diary_network
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin_data:

networks:
  emotional_diary_network:
    driver: bridge 